name: Deploy Page
on:
    release:
        types: [published]

jobs:
    deploy-page:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Configure AWS Creds
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-2

            - name: Deploy
              run: aws s3 sync ./frontend/ s3://lakehouse.sickendick.com/power_sensor --delete
